version: '3.2'
services:
  admin:
    image: mentorpal/mentor-admin:4.3.0-alpha.6
    environment:
      - NODE_ENV
      - GRAPHQL_ENDPOINT=http://graphql:3001/graphql
    depends_on:
      - graphql
    volumes:
      - type: bind
        source: ./build/run/.env
        target: /app/.env
  classifier:
    image: mentorpal/mentor-classifier-api:4.4.0-alpha.4
    links:
      - graphql
    environment:
      - CELERY_RESULT_BACKEND
      - CLASSIFIER_ARCH=mentor_classifier.arch.lr_transformer
      - CLASSIFIER_CELERY_BROKER_URL
      - CLASSIFIER_QUEUE_NAME
      - GRAPHQL_ENDPOINT=http://graphql:3001/graphql
      - MODEL_ROOT
      - SHARED_ROOT
      - STATUS_URL_FORCE_HTTPS
    volumes:
      - type: bind
        source: ./build/run/.env
        target: /app/.env
      - type: bind
        source: ./models
        target: /app/models
        read_only: true
      - type: bind
        source: ./shared
        target: /app/shared
        read_only: true
  chat:
    image: mentorpal/mentor-client:4.2.0
    environment:
      - MENTOR_API_URL=/classifier
    depends_on:
      - classifier
    volumes:
      - type: bind
        source: ./build/run/.env
        target: /app/.env
  graphql:
    image: mentorpal/mentor-graphql:4.2.0
    environment:
      - NODE_ENV
      - MONGO_URI
    volumes:
      - type: bind
        source: ./build/run/.env
        target: /app/.env
  nginx:
    image: nginx:1-alpine
    ports:
      - 80:80
    depends_on:
      - admin
      - chat
      - classifier
      - graphql
      - upload-api
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./nginx/conf.d
        target: /etc/nginx/conf.d
  training:
    image: mentorpal/mentor-classifier:4.4.0-alpha.4
    depends_on:
      - graphql
    entrypoint: /app/training_worker.sh
    environment:
      - CELERY_RESULT_BACKEND
      - CLASSIFIER_ARCH=mentor_classifier.arch.lr_transformer
      - CLASSIFIER_CELERY_BROKER_URL
      - CLASSIFIER_QUEUE_NAME
      - GRAPHQL_ENDPOINT=http://graphql:3001/graphql
      - LOG_LEVEL_CLASSIFIER=DEBUG
      - MODEL_ROOT
      - SHARED_ROOT
    links:
      - graphql
    volumes:
      - type: bind
        source: ./build/run/.env
        target: /app/.env
      - type: bind
        source: ./models
        target: /app/models
      - type: bind
        source: ./shared
        target: /app/shared
        read_only: true
  upload-api:
    image: mentorpal/mentor-upload-api:4.4.0-alpha.2
    environment:
      - UPLOAD_CELERY_BROKER_URL
      - UPLOAD_QUEUE_NAME
    volumes:
      - type: bind
        source: ./build/run/.env
        target: /app/.env
      - type: bind
        source: ./uploads
        target: /app/uploads
  upload-worker:
    image: mentorpal/mentor-upload-worker:4.4.0-alpha.2
    depends_on:
      - graphql
    environment:
      - GRAPHQL_ENDPOINT=http://graphql:3001/graphql
      - TRANSCRIBE_MODULE_PATH=transcribe_aws
      - UPLOAD_CELERY_BROKER_URL
      - UPLOAD_QUEUE_NAME
    links:
      - graphql
    volumes:
      - type: bind
        source: ./build/run/.env
        target: /app/.env
      - type: bind
        source: ./uploads
        target: /app/uploads
